import wx
import WxPythonEnhancements


class ThisUI:
    def __init__(self):
        super().__init__()
        self.main_frame=wx.Frame(parent=None, title='sizerdemo')
        self.main_panel=wx.Panel(parent=self.main_frame)
        self.main_panel.BackgroundColour=wx.Colour(255, 255,0)
        self.main_sizer=wx.BoxSizer(orient=wx.VERTICAL)
        self.main_sizer.attach_sizer_to_window(self.main_panel)
        self.panel1=wx.Panel(style=wx.BORDER_RAISED, parent=self.main_panel)
        self.panel1.BackgroundColour=wx.Colour(200,200,255)
        self.statictext1=wx.StaticText(label='StaticText1', style=wx.BORDER_SIMPLE, parent=self.panel1)
        self.statictext1.BackgroundColour=wx.Colour(0,255,0)
        self.statictext2=wx.StaticText(label='StaticText2', style=wx.BORDER_SIMPLE, parent=self.panel1)
        self.statictext2.BackgroundColour=wx.Colour(0,255,0)
        self.statictext3=wx.StaticText(label='StaticText3', style=wx.BORDER_SIMPLE, parent=self.panel1)
        self.statictext3.BackgroundColour=wx.Colour(0,255,0)
        self.var1=wx.BoxSizer(orient=wx.HORIZONTAL)
        self.panel1.SetSizer(self.var1)
        self.var3=wx.SizerItem(width=0, height=0, proportion=1)
        wx.Sizer.Add(self.var1, self.var3)
        self.var5=wx.SizerItem(window=self.statictext1, proportion=0)
        wx.Sizer.Add(self.var1, self.var5)
        self.var7=wx.SizerItem(width=0, height=0, proportion=1)
        wx.Sizer.Add(self.var1, self.var7)
        self.var9=wx.SizerItem(window=self.statictext2, proportion=0)
        wx.Sizer.Add(self.var1, self.var9)
        self.var11=wx.SizerItem(width=0, height=0, proportion=1)
        wx.Sizer.Add(self.var1, self.var11)
        self.var13=wx.SizerItem(window=self.statictext3, proportion=0)
        wx.Sizer.Add(self.var1, self.var13)
        self.var15=wx.SizerItem(width=0, height=0, proportion=1)
        wx.Sizer.Add(self.var1, self.var15)
        self.panel2=wx.Panel(style=wx.BORDER_RAISED, parent=self.main_panel)
        self.panel2.BackgroundColour=wx.Colour(255,200,200)
        self.statictext2_1=wx.StaticText(label='StaticText2_1', style=wx.BORDER_SIMPLE, parent=self.panel2)
        self.statictext2_1.BackgroundColour=wx.Colour(0,255,0)
        self.statictext2_2=wx.StaticText(label='StaticText2_2', style=wx.BORDER_SIMPLE, parent=self.panel2)
        self.statictext2_2.BackgroundColour=wx.Colour(0,255,0)
        self.statictext2_3=wx.StaticText(label='StaticText2_3', style=wx.BORDER_SIMPLE, parent=self.panel2)
        self.statictext2_3.BackgroundColour=wx.Colour(0,255,0)
        self.var17=wx.SizerItem(window=self.panel1, flag=wx.EXPAND, proportion=1)
        self.main_sizer.Add(self.var17)
        self.var19=wx.SizerItem(window=self.panel2, flag=wx.EXPAND, proportion=1)
        self.main_sizer.Add(self.var19)
        self.var21=wx.BoxSizer(orient=wx.HORIZONTAL)
        self.var21.attach_sizer_to_window(self.panel2)
        self.var23=wx.SizerItem(window=self.statictext2_1, proportion=1)
        wx.Sizer.Add(self.var21, self.var23)
        self.var25=wx.SizerItem(window=self.statictext2_2, flag=wx.CENTER, proportion=2)
        wx.Sizer.Add(self.var21, self.var25)
        self.var27=wx.SizerItem(window=self.statictext2_3, flag=wx.ALIGN_BOTTOM, proportion=3)
        wx.Sizer.Add(self.var21, self.var27)


if __name__ == '__main__':
    def main():
        app = wx.App()
        ui = ThisUI()
        ui.main_frame.Show()
        app.MainLoop()


    main()
